Repository hyperlight-dev/hyperlight, pull requests merged in 2024-11, with the labels that each got.

#24 clean up a dapr reference in contrib.md
  CONTRIBUTING.md
Labels: documentation

#27 [chore] Modifying logo image in README to use an absolute path
  README.md
Labels: chore

#33 Update README
  README.md
Labels: documentation

#32 [github-actions] Made it so tests also run on intel
  .github/workflows/Benchmarks.yml
  .github/workflows/CreateRelease.yml
  .github/workflows/dep_rust.yml
  Justfile
Labels: github-actions

#38 [github-actions] minor fix to release
  .github/workflows/CreateRelease.yml
Labels: bug, github-actions

#39 [github-actions] minor fix to release
  .github/workflows/CreateRelease.yml
Labels: github-actions

#36 [documentation] small README changes
  README.md
  docs/assets/hyperlight-logo.png
  docs/assets/hyperlight-logo.xcf
Labels: documentation

#44 Ignore markdown and txt files in CI
  .github/workflows/ValidatePullRequest.yml
Labels: chore

#48 Fix docs only CI job processing
  .github/workflows/ValidatePullRequest.yml
  .github/workflows/dep_fuzzing.yml
  .github/workflows/dep_rust.yml
  src/tests/rust_guests/callbackguest/Cargo.lock
  src/tests/rust_guests/simpleguest/Cargo.lock
Labels: bug, chore

#43 docs: fix typo
  README.md
Labels: documentation

#53 Update to common workflow
  .github/workflows/Benchmarks.yml
  .github/workflows/CargoPublish.yml
  .github/workflows/CreateRelease.yml
  .github/workflows/ValidatePullRequest.yml
  .github/workflows/dep_build_guest_binaries.yml
  .github/workflows/dep_fuzzing.yml
  .github/workflows/dep_rust.yml
Labels: github-actions

#55 Improve error when guest binary not found
  src/hyperlight_host/src/sandbox/uninitialized.rs
Labels: enhancement

#56 Improve docs
  README.md
  docs/README.md
  docs/how-to-use-flatbuffers.md
  docs/security.md
Labels: documentation

#58 Run spell checks on the repo
  .github/workflows/ValidatePullRequest.yml
  Justfile
  NOTICE.txt
  src/hyperlight_common/src/flatbuffer_wrappers/guest_log_level.rs
  src/hyperlight_host/benches/benchmarks.rs
  src/hyperlight_host/src/error.rs
  src/hyperlight_host/src/func/call_ctx.rs
  src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
  src/hyperlight_host/src/hypervisor/kvm.rs
  src/hyperlight_host/src/hypervisor/metrics.rs
  src/hyperlight_host/src/hypervisor/surrogate_process_manager.rs
  src/hyperlight_host/src/mem/exe.rs
  src/hyperlight_host/src/mem/layout.rs
  src/hyperlight_host/src/mem/loaded_lib.rs
  src/hyperlight_host/src/mem/mgr.rs
  src/hyperlight_host/src/mem/mod.rs
  src/hyperlight_host/src/mem/pe/mod.rs
  src/hyperlight_host/src/mem/shared_mem.rs
  src/hyperlight_host/src/metrics/mod.rs
  src/hyperlight_host/src/sandbox/initialized_multi_use.rs
  src/hyperlight_host/src/sandbox/initialized_single_use.rs
  src/hyperlight_host/src/sandbox/metrics.rs
  src/hyperlight_host/src/sandbox/mod.rs
  src/hyperlight_host/src/sandbox/outb.rs
  src/hyperlight_host/src/sandbox/uninitialized.rs
  src/hyperlight_host/src/sandbox_state/mod.rs
  src/hyperlight_host/src/sandbox_state/sandbox.rs
  src/hyperlight_host/src/testing/log_values.rs
  src/hyperlight_host/tests/common/mod.rs
  src/schema/function_call.fbs
  src/schema/function_types.fbs
  typos.toml
Labels: documentation

#54 Add devcontainer config
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/setup.sh
  .github/workflows/CreateDevcontainerImage.yml
  .gitignore
  README.md
Labels: github-actions

#60 Fix README links
  docs/README.md
Labels: documentation

#65 [dependencies] add Cargo.lock
  .gitignore
  Cargo.lock
  src/hyperlight_host/Cargo.toml
  src/hyperlight_testing/Cargo.toml
Labels: dependencies

#68 [documentation] fix broken links in docs/README.md
  docs/README.md
Labels: documentation

#69 [documentation] adding MAINTAINERS file
  MAINTAINERS.md
Labels: documentation

#66 remove .vscode settings
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  CONTRIBUTING.md
Labels: chore

#25 Create the hyperlight proposal process
  proposals/0000-hip-process/README.md
  proposals/NNNN-hip-template/README.md
  proposals/README.md
Labels: documentation

#77 [github_actions] update PRLabelChecker workflow to pull new labels
  .github/workflows/PRLabelChecker.yml
Labels: github_actions

#74 Fix 'download benchmark' workflow
  .github/workflows/Benchmarks.yml
  .github/workflows/dep_rust.yml
Labels: bug, github_actions

#73 Avoid eagerly doing unnecessary string formatting
  .github/workflows/dep_rust.yml
  src/hyperlight_host/src/mem/elf.rs
Labels: performance

#79 [ci] Cancel in-progress jobs for new pushes
  .github/workflows/ValidatePullRequest.yml
Labels: github_actions

#26 [performance] Move `set_up_hypervisor_partition` to inside the hv handler thread
  src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
Labels: performance

#84 [docs] small patch to HIP template
  proposals/NNNN-hip-template/README.md
Labels: documentation

#61 Fix otlp tracing
  Cargo.lock
  docs/hyperlight-metrics-logs-and-traces.md
  src/hyperlight_host/Cargo.toml
  src/hyperlight_host/examples/otlp_tracing/main.rs
Labels: bug, dependencies
