Repository hyperlight-dev/hyperlight, pull requests merged in 2025-07, with the labels that each got.

#678 gdb: fix issue "Debug not enabled" when `gdb` feature was enabled
  src/hyperlight_host/examples/guest-debugging/main.rs
  src/hyperlight_host/src/hypervisor/hyperv_linux.rs
  src/hyperlight_host/src/hypervisor/hyperv_windows.rs
  src/hyperlight_host/src/hypervisor/kvm.rs
  src/tests/rust_guests/witguest/Cargo.lock
Labels: kind/bugfix

#679 Switch 'deny' lints to 'warn'
  src/hyperlight_host/src/lib.rs
  src/hyperlight_host/src/sandbox/hypervisor.rs
Labels: kind/enhancement

#675 Update paging-development-notes.md
  docs/paging-development-notes.md
Labels: area/documentation, kind/enhancement

#674 Update README.md
  docs/README.md
Labels: area/documentation, kind/enhancement

#672 Clippy updates
  .github/workflows/dep_rust.yml
  Justfile
  hack/clippy-package-features.sh
  src/hyperlight_guest/src/guest_handle/handle.rs
  src/hyperlight_guest/src/guest_handle/host_comm.rs
  src/hyperlight_guest_bin/src/exceptions/handler.rs
  src/hyperlight_guest_bin/src/exceptions/idtr.rs
  src/hyperlight_guest_bin/src/guest_function/call.rs
  src/hyperlight_guest_bin/src/host_comm.rs
  src/hyperlight_guest_bin/src/lib.rs
  src/hyperlight_guest_bin/src/paging.rs
Labels: area/infrastructure, kind/refactor, github_actions

#725 Make MultiUseSandbox::map_file_cow public
  src/hyperlight_host/src/sandbox/initialized_multi_use.rs
Labels: kind/enhancement

#746 Restrict restoring sandboxes to snapshot taken on self
  src/hyperlight_host/src/error.rs
  src/hyperlight_host/src/mem/mgr.rs
  src/hyperlight_host/src/mem/shared_mem_snapshot.rs
  src/hyperlight_host/src/sandbox/initialized_multi_use.rs
Labels: kind/bugfix

#748 Adds blocker to release if any issue has release-blocker label
  .github/workflows/CreateRelease.yml
  .github/workflows/ReleaseBlockerCheck.yml
  .github/workflows/ReleaseBlockerLabelCleanUp.yml
  dev/check-release-blockers.sh
  docs/github-labels.md
Labels: kind/enhancement
