Repository hyperlight-dev/hyperlight, pull requests merged in 2025-05, with the labels that each got.

#447 update release flow - Don't publish testing guest-binaries on release
  .github/workflows/CreateRelease.yml
Labels: kind/enhancement, area/infrastructure

#449 Add GH_TOKEN env to release workflow
  .github/workflows/CreateRelease.yml
Labels: kind/bugfix, area/infrastructure

#452 Add benchmark for guest call with large parameters
  src/hyperlight_host/benches/benchmarks.rs
  src/tests/rust_guests/simpleguest/src/main.rs
Labels: kind/enhancement, area/performance

#439 Fix: Correct typo in `simpleguest` rust example
  src/tests/rust_guests/simpleguest/src/main.rs
Labels: kind/enhancement

#460 Add error logging when MapViewOfFileNuma2 fails
  src/hyperlight_host/src/hypervisor/surrogate_process_manager.rs
Labels: kind/enhancement

#464 Unify HostFunctionXX traits into a single HostFunction
  src/hyperlight_host/benches/benchmarks.rs
  src/hyperlight_host/examples/guest-debugging/main.rs
  src/hyperlight_host/examples/hello-world/main.rs
  src/hyperlight_host/src/func/guest_dispatch.rs
  src/hyperlight_host/src/func/host_functions.rs
  src/hyperlight_host/src/func/mod.rs
  src/hyperlight_host/src/sandbox/uninitialized.rs
  src/hyperlight_host/tests/common/mod.rs
  src/hyperlight_host/tests/sandbox_host_tests.rs
Labels: kind/enhancement, area/API

#466 Update to include CNCF sandbox project text
  README.md
Labels: area/documentation, kind/enhancement

#467 Remove dependency on the paste crate
  Cargo.lock
  src/hyperlight_host/Cargo.toml
  src/hyperlight_host/src/mem/layout.rs
Labels: area/dependencies, kind/dependencies

#468 Improve the ergonomics of registering host functions
  README.md
  src/hyperlight_host/benches/benchmarks.rs
  src/hyperlight_host/examples/guest-debugging/main.rs
  src/hyperlight_host/examples/hello-world/main.rs
  src/hyperlight_host/src/func/guest_dispatch.rs
  src/hyperlight_host/src/func/host_functions.rs
  src/hyperlight_host/src/sandbox/uninitialized.rs
  src/hyperlight_host/tests/sandbox_host_tests.rs
Labels: kind/enhancement, area/API

#473 Adding code owners file
  .github/CODEOWNERS
Labels: area/documentation, kind/enhancement, area/infrastructure

#475 Remove generics from SupportedParameterType and SupportedReturnType traits
  src/hyperlight_host/src/func/host_functions.rs
  src/hyperlight_host/src/func/param_type.rs
  src/hyperlight_host/src/func/ret_type.rs
Labels: kind/refactor

#476 Improve ergonomics of SupportedParameterType and SupportedReturnType
  src/hyperlight_common/src/flatbuffer_wrappers/function_types.rs
  src/hyperlight_host/src/func/host_functions.rs
  src/hyperlight_host/src/func/param_type.rs
  src/hyperlight_host/src/func/ret_type.rs
Labels: kind/refactor

#456 Gdb debug improvements
  src/hyperlight_host/src/hypervisor/gdb/arch.rs
  src/hyperlight_host/src/hypervisor/gdb/event_loop.rs
  src/hyperlight_host/src/hypervisor/gdb/kvm_debug.rs
  src/hyperlight_host/src/hypervisor/gdb/mod.rs
  src/hyperlight_host/src/hypervisor/gdb/mshv_debug.rs
  src/hyperlight_host/src/hypervisor/hyperv_linux.rs
Labels: kind/refactor

#479 Remove unused FunctionDefinition and redundant FunctionsMap
  src/hyperlight_host/src/func/host_functions.rs
  src/hyperlight_host/src/sandbox/host_funcs.rs
  src/hyperlight_host/src/sandbox/mod.rs
Labels: kind/refactor

#480 Refactor HostFuncsWrapper
  src/hyperlight_host/src/sandbox/host_funcs.rs
  src/hyperlight_host/src/sandbox/initialized_multi_use.rs
  src/hyperlight_host/src/sandbox/outb.rs
  src/hyperlight_host/src/sandbox/uninitialized.rs
  src/hyperlight_host/src/sandbox/uninitialized_evolve.rs
  src/hyperlight_host/src/seccomp/guest.rs
Labels: kind/refactor

#485 Remove support from hyperlight_host for PE formatted guests
  src/hyperlight_host/src/error.rs
  src/hyperlight_host/src/func/guest_dispatch.rs
  src/hyperlight_host/src/mem/exe.rs
  src/hyperlight_host/src/mem/loaded_lib.rs
  src/hyperlight_host/src/mem/mgr.rs
  src/hyperlight_host/src/mem/mod.rs
  src/hyperlight_host/src/mem/pe/base_relocations.rs
  src/hyperlight_host/src/mem/pe/headers.rs
  src/hyperlight_host/src/mem/pe/mod.rs
  src/hyperlight_host/src/mem/pe/pe_info.rs
  src/hyperlight_host/src/sandbox/config.rs
  src/hyperlight_host/src/sandbox/uninitialized.rs
  src/hyperlight_host/src/testing/mod.rs
  src/hyperlight_host/tests/common/mod.rs
  src/hyperlight_host/tests/sandbox_host_tests.rs
  src/hyperlight_testing/src/lib.rs
Labels: area/infrastructure, kind/refactor

#484 Update README.md with Copyright text for LF projects
  README.md
Labels: area/documentation, kind/enhancement

#490 Remove in process mode from hyperlight-host
  .github/workflows/dep_rust.yml
  Justfile
  docs/debugging-hyperlight.md
  src/hyperlight_host/Cargo.toml
  src/hyperlight_host/build.rs
  src/hyperlight_host/src/func/guest_dispatch.rs
  src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
  src/hyperlight_host/src/hypervisor/mod.rs
  src/hyperlight_host/src/mem/custom_drop.rs
  src/hyperlight_host/src/mem/layout.rs
  src/hyperlight_host/src/mem/mgr.rs
  src/hyperlight_host/src/mem/mod.rs
  src/hyperlight_host/src/mem/shared_mem.rs
  src/hyperlight_host/src/sandbox/leaked_outb.rs
  src/hyperlight_host/src/sandbox/mem_mgr.rs
  src/hyperlight_host/src/sandbox/mod.rs
  src/hyperlight_host/src/sandbox/outb.rs
  src/hyperlight_host/src/sandbox/uninitialized.rs
  src/hyperlight_host/src/sandbox_state/sandbox.rs
  src/hyperlight_host/tests/common/mod.rs
  src/hyperlight_host/tests/integration_test.rs
  src/hyperlight_host/tests/sandbox_host_tests.rs
Labels: kind/enhancement

#487 Remove `host_print_writer` from the arguments to `UninitializedSandbox::new`
  README.md
  fuzz/fuzz_targets/guest_call.rs
  fuzz/fuzz_targets/host_call.rs
  fuzz/fuzz_targets/host_print.rs
  src/hyperlight_host/benches/benchmarks.rs
  src/hyperlight_host/examples/func_ctx/main.rs
  src/hyperlight_host/examples/guest-debugging/main.rs
  src/hyperlight_host/examples/hello-world/main.rs
  src/hyperlight_host/examples/logging/main.rs
  src/hyperlight_host/examples/metrics/main.rs
  src/hyperlight_host/examples/tracing-chrome/main.rs
  src/hyperlight_host/examples/tracing-otlp/main.rs
  src/hyperlight_host/examples/tracing-tracy/main.rs
  src/hyperlight_host/examples/tracing/main.rs
  src/hyperlight_host/src/func/call_ctx.rs
  src/hyperlight_host/src/func/guest_dispatch.rs
  src/hyperlight_host/src/func/host_functions.rs
  src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
  src/hyperlight_host/src/hypervisor/mod.rs
  src/hyperlight_host/src/metrics/mod.rs
  src/hyperlight_host/src/sandbox/initialized_multi_use.rs
  src/hyperlight_host/src/sandbox/mod.rs
  src/hyperlight_host/src/sandbox/uninitialized.rs
  src/hyperlight_host/src/sandbox/uninitialized_evolve.rs
  src/hyperlight_host/tests/common/mod.rs
  src/hyperlight_host/tests/integration_test.rs
  src/hyperlight_host/tests/sandbox_host_tests.rs
Labels: kind/refactor, area/API

#496 Remove in-process mode from hyperlight-guest and remaining clean up in hyperlight-host
  README.md
  fuzz/fuzz_targets/guest_call.rs
  fuzz/fuzz_targets/host_call.rs
  fuzz/fuzz_targets/host_print.rs
  src/hyperlight_common/src/mem.rs
  src/hyperlight_guest/src/chkstk.rs
  src/hyperlight_guest/src/entrypoint.rs
  src/hyperlight_guest/src/guest_error.rs
  src/hyperlight_guest/src/host_function_call.rs
  src/hyperlight_guest/src/lib.rs
  src/hyperlight_host/benches/benchmarks.rs
  src/hyperlight_host/examples/func_ctx/main.rs
  src/hyperlight_host/examples/guest-debugging/main.rs
  src/hyperlight_host/examples/hello-world/main.rs
  src/hyperlight_host/examples/logging/main.rs
  src/hyperlight_host/examples/metrics/main.rs
  src/hyperlight_host/examples/tracing-chrome/main.rs
  src/hyperlight_host/examples/tracing-otlp/main.rs
  src/hyperlight_host/examples/tracing-tracy/main.rs
  src/hyperlight_host/examples/tracing/main.rs
  src/hyperlight_host/src/func/call_ctx.rs
  src/hyperlight_host/src/func/guest_dispatch.rs
  src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
  src/hyperlight_host/src/hypervisor/inprocess.rs
  src/hyperlight_host/src/hypervisor/mod.rs
  src/hyperlight_host/src/lib.rs
  src/hyperlight_host/src/mem/layout.rs
  src/hyperlight_host/src/mem/mgr.rs
  src/hyperlight_host/src/metrics/mod.rs
  src/hyperlight_host/src/sandbox/initialized_multi_use.rs
  src/hyperlight_host/src/sandbox/mod.rs
  src/hyperlight_host/src/sandbox/run_options.rs
  src/hyperlight_host/src/sandbox/uninitialized.rs
  src/hyperlight_host/src/sandbox/uninitialized_evolve.rs
  src/hyperlight_host/tests/common/mod.rs
  src/hyperlight_host/tests/integration_test.rs
  src/hyperlight_host/tests/sandbox_host_tests.rs
Labels: kind/enhancement

#491 Refactor HostFunction
  src/hyperlight_host/src/func/host_functions.rs
  src/hyperlight_host/src/func/mod.rs
  src/hyperlight_host/src/func/param_type.rs
  src/hyperlight_host/src/func/ret_type.rs
  src/hyperlight_host/src/func/utils.rs
  src/hyperlight_host/src/sandbox/host_funcs.rs
  src/hyperlight_host/src/sandbox/uninitialized.rs
  src/hyperlight_host/tests/common/mod.rs
  src/hyperlight_host/tests/sandbox_host_tests.rs
Labels: kind/refactor, area/API

#500 guest: make `call_host_function` generic to avoid two steps to retrieve return value
  src/hyperlight_guest/src/host_function_call.rs
  src/hyperlight_guest/src/print.rs
  src/hyperlight_guest_capi/src/dispatch.rs
  src/hyperlight_host/src/func/utils.rs
  src/hyperlight_host/src/sandbox/initialized_multi_use.rs
  src/tests/rust_guests/callbackguest/src/main.rs
  src/tests/rust_guests/simpleguest/src/main.rs
Labels: kind/enhancement

#507 Prevent hyperlight_guest from always rebuilding even with no new updates
  src/hyperlight_guest/build.rs
Labels: kind/bugfix, area/infrastructure

#511 Update copilot-instructions
  .github/copilot-instructions.md
Labels: kind/enhancement

#514 Fix typo in path to docs/github-labels.md
  .github/copilot-instructions.md
Labels: kind/enhancement

#515 Make sure copilot gpg signs and signs-off commits
  .github/copilot-instructions.md
Labels: kind/enhancement

#531 Fix breaking changes for hyperlight js
  src/hyperlight_guest/third_party/musl/arch/x86_64/bits/setjmp.h
  src/hyperlight_host/Cargo.toml
  src/hyperlight_host/src/error.rs
Labels: kind/dependencies

#538 Prepare for v0.5.0 release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/tests/rust_guests/callbackguest/Cargo.lock
  src/tests/rust_guests/simpleguest/Cargo.lock
Labels: kind/dependencies

#494 Use native types when calling host functions
  README.md
  fuzz/fuzz_targets/guest_call.rs
  fuzz/fuzz_targets/host_call.rs
  fuzz/fuzz_targets/host_print.rs
  src/hyperlight_host/benches/benchmarks.rs
  src/hyperlight_host/examples/func_ctx/main.rs
  src/hyperlight_host/examples/guest-debugging/main.rs
  src/hyperlight_host/examples/hello-world/main.rs
  src/hyperlight_host/examples/logging/main.rs
  src/hyperlight_host/examples/metrics/main.rs
  src/hyperlight_host/examples/tracing-chrome/main.rs
  src/hyperlight_host/examples/tracing-otlp/main.rs
  src/hyperlight_host/examples/tracing-tracy/main.rs
  src/hyperlight_host/examples/tracing/main.rs
  src/hyperlight_host/src/func/call_ctx.rs
  src/hyperlight_host/src/func/guest_dispatch.rs
  src/hyperlight_host/src/func/param_type.rs
  src/hyperlight_host/src/func/ret_type.rs
  src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
  src/hyperlight_host/src/metrics/mod.rs
  src/hyperlight_host/src/sandbox/host_funcs.rs
  src/hyperlight_host/src/sandbox/initialized_multi_use.rs
  src/hyperlight_host/src/seccomp/guest.rs
  src/hyperlight_host/tests/integration_test.rs
  src/hyperlight_host/tests/sandbox_host_tests.rs
Labels: kind/enhancement, area/API
