Repository hyperlight-dev/hyperlight, pull requests merged in 2025-01, with the labels that each got.

#124 Bump kvm-ioctl to 0.19.1
  Cargo.lock
  src/hyperlight_host/Cargo.toml
Labels: dependencies

#126 Fail CI if Cargo.lock is not up-to-date
  .github/workflows/dep_rust.yml
  src/tests/rust_guests/callbackguest/Cargo.lock
  src/tests/rust_guests/simpleguest/Cargo.lock
Labels: github_actions

#128 Minor doc update
  README.md
Labels: documentation

#142 Update security.md
  docs/security.md
Labels: documentation

#141 Update security.md
  docs/security.md
Labels: documentation

#140 Update glossary.md
  docs/glossary.md
Labels: documentation

#139 Update glossary.md
  docs/glossary.md
Labels: documentation

#155 Adds a script for KVM perf issue mitigation on 6.x kernel
  src/hyperlight_host/scripts/apply-kvm-perf-mitigation.sh
Labels: bug

#125 Remove SingleUseSandbox
  src/hyperlight_host/examples/chrome-tracing/main.rs
  src/hyperlight_host/src/func/call_ctx.rs
  src/hyperlight_host/src/func/guest_dispatch.rs
  src/hyperlight_host/src/lib.rs
  src/hyperlight_host/src/sandbox/initialized_single_use.rs
  src/hyperlight_host/src/sandbox/mod.rs
  src/hyperlight_host/src/sandbox/run_options.rs
  src/hyperlight_host/src/sandbox/uninitialized.rs
  src/hyperlight_host/src/sandbox/uninitialized_evolve.rs
  src/hyperlight_host/src/sandbox_state/sandbox.rs
  src/hyperlight_host/tests/integration_test.rs
Labels: breaking-change

#153 reduce number of threads in simple_test_parallel test function
  src/hyperlight_host/tests/sandbox_host_tests.rs
Labels: bug

#163 Update dependabot to check on test guest directories
  .github/dependabot.yml
Labels: dependencies

#134 Updates PR workflow to remove superfluous jobs
  .github/workflows/ValidatePullRequest.yml
  .github/workflows/dep_rust.yml
Labels: github_actions

#106 Remove custom alloca
  src/hyperlight_guest/Cargo.toml
  src/hyperlight_guest/build.rs
  src/hyperlight_guest/src/alloca.rs
  src/hyperlight_guest/src/alloca/alloca.c
  src/hyperlight_guest/src/lib.rs
  src/hyperlight_host/examples/func_ctx/main.rs
  src/hyperlight_host/src/func/call_ctx.rs
  src/hyperlight_host/src/sandbox/initialized_multi_use.rs
  src/hyperlight_host/tests/integration_test.rs
  src/tests/c_guests/c_simpleguest/main.c
  src/tests/rust_guests/simpleguest/src/main.rs
Labels: breaking-change

#93 Issue template for reporting bugs
  .github/ISSUE_TEMPLATE/bug.yaml
Labels: documentation

#108 Removes requirement of specific environment variables during testing
  .devcontainer/devcontainer.json
  src/hyperlight_host/src/hypervisor/hyperv_linux.rs
  src/hyperlight_host/src/hypervisor/kvm.rs
  src/hyperlight_host/src/sandbox/mod.rs
Labels: enhancement

#178 Add clarification on why we must take GuestSharedMemory::lock
  src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
  src/hyperlight_host/src/mem/shared_mem.rs
Labels: documentation

#205 Updates to otel 0.27.1
  Cargo.lock
  src/hyperlight_host/Cargo.toml
  src/hyperlight_host/examples/otlp_tracing/main.rs
Labels: area/dependencies

#154 Add a check for dependabot PR updating guest or common lib dependencies
  .github/workflows/ValidatePullRequest.yml
Labels: area/dependencies

#213 update kvm-ioctls and kvm-bindings to latest versions
  Cargo.lock
  src/hyperlight_host/Cargo.toml
Labels: area/dependencies

#226 Update label checker for new lifecycle labels
  .github/workflows/IssueLabelChecker.yml
Labels: kind/infrastructure
