Repository hyperlight-dev/hyperlight, pull requests merged in 2025-02, with the labels that each got.

#214 Updates rand crate to 0.9
  Cargo.lock
  src/hyperlight_host/Cargo.toml
  src/hyperlight_host/examples/otlp_tracing/main.rs
  src/hyperlight_host/src/hypervisor/surrogate_process_manager.rs
  src/hyperlight_host/src/mem/layout.rs
  src/hyperlight_host/src/sandbox/uninitialized_evolve.rs
Labels: area/dependencies

#208 Reset guest memory when guest function fails
  src/hyperlight_host/src/sandbox/initialized_multi_use.rs
  src/hyperlight_host/tests/integration_test.rs
  src/tests/rust_guests/simpleguest/src/main.rs
Labels: kind/bug

#231 Adding community meeting info to our README.md
  README.md
Labels: kind/documentation

#227 Update Cargo.lock for dependency updates in common crates
  .github/workflows/ValidatePullRequest.yml
Labels: area/dependencies

#235 checkout the repo if common dependencies changed
  .github/workflows/ValidatePullRequest.yml
Labels: kind/infrastructure

#236 Make sure to checkout PR branch
  .github/workflows/ValidatePullRequest.yml
Labels: kind/infrastructure

#240 Dont check cargo lock for Rust test guest
  .github/workflows/ValidatePullRequest.yml
  .github/workflows/dep_rust.yml
Labels: area/process

#234 Fix issues with using `CreateMapViewOfFile` with `inprocess` feature
  src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
  src/hyperlight_host/src/mem/shared_mem.rs
Labels: kind/bugfix

#233 Fix CI passing with failing tests
  .github/workflows/dep_rust.yml
Labels: area/process

#268 Fix typos that are causing all PRs to fail CI
  src/hyperlight_host/benches/benchmarks.rs
Labels: kind/bugfix

#269 Fix typos version
  .github/workflows/ValidatePullRequest.yml
Labels: area/dependencies

#254 add back minimal vscode settings file for rust-analyzer
  .gitignore
  .vscode/settings.json
Labels: rust

#262 opentelemetry dependency updates
  Cargo.lock
  src/hyperlight_host/Cargo.toml
  src/hyperlight_host/examples/otlp_tracing/main.rs
Labels: area/dependencies

#273 update the tests Cargo.lock to reflect dependabot change
  src/tests/rust_guests/callbackguest/Cargo.lock
  src/tests/rust_guests/simpleguest/Cargo.lock
Labels: area/process

#111 Add support for Hyperlight KVM guest debugging using gdb
  .github/workflows/dep_rust.yml
  Cargo.lock
  Justfile
  docs/README.md
  docs/how-to-debug-a-hyperlight-guest.md
  src/hyperlight_host/Cargo.toml
  src/hyperlight_host/build.rs
  src/hyperlight_host/examples/guest-debugging/main.rs
  src/hyperlight_host/src/error.rs
  src/hyperlight_host/src/hypervisor/gdb/event_loop.rs
  src/hyperlight_host/src/hypervisor/gdb/mod.rs
  src/hyperlight_host/src/hypervisor/gdb/x86_64_target.rs
  src/hyperlight_host/src/hypervisor/handlers.rs
  src/hyperlight_host/src/hypervisor/hyperv_linux.rs
  src/hyperlight_host/src/hypervisor/hyperv_windows.rs
  src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
  src/hyperlight_host/src/hypervisor/inprocess.rs
  src/hyperlight_host/src/hypervisor/kvm.rs
  src/hyperlight_host/src/hypervisor/mod.rs
  src/hyperlight_host/src/mem/layout.rs
  src/hyperlight_host/src/mem/shared_mem.rs
  src/hyperlight_host/src/sandbox/config.rs
  src/hyperlight_host/src/sandbox/mem_access.rs
  src/hyperlight_host/src/sandbox/uninitialized.rs
  src/hyperlight_host/src/sandbox/uninitialized_evolve.rs
Labels: kind/enhancement

#283 Bump hyperlight version to 0.2.0
  Cargo.lock
  Cargo.toml
  src/tests/rust_guests/callbackguest/Cargo.lock
  src/tests/rust_guests/simpleguest/Cargo.lock
Labels: area/process

#290 Fix mshv crates version to 0.3.2
  src/hyperlight_host/Cargo.toml
Labels: area/dependencies

#259 Generic guest/host result API
  src/hyperlight_common/src/flatbuffer_wrappers/util.rs
  src/hyperlight_guest/src/host_function_call.rs
  src/hyperlight_guest_capi/src/flatbuffer.rs
  src/tests/rust_guests/callbackguest/src/main.rs
  src/tests/rust_guests/simpleguest/src/main.rs
Labels: kind/refactor

#237 Run clippy on guests in CI
  .github/workflows/dep_rust.yml
  Justfile
  src/hyperlight_guest/src/guest_function_call.rs
  src/hyperlight_guest/src/guest_function_definition.rs
  src/hyperlight_guest_capi/src/dispatch.rs
  src/tests/rust_guests/callbackguest/src/main.rs
  src/tests/rust_guests/simpleguest/src/main.rs
Labels: breaking-change
