Repository hyperlight-dev/hyperlight, pull requests merged in 2025-06, with the labels that each got.

#547 Update kvm-ioctls crate to 0.22 and kvm-bindings crate to 0.12
  Cargo.lock
  src/hyperlight_host/Cargo.toml
Labels: kind/dependencies

#558 Bump version to 0.5.1 and add changelog
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/tests/rust_guests/callbackguest/Cargo.lock
  src/tests/rust_guests/simpleguest/Cargo.lock
Labels: kind/enhancement

#554 Update open telemetry crates to latest versions
  Cargo.lock
  src/hyperlight_host/Cargo.toml
Labels: kind/dependencies

#570 Automatically install guest cross-compilation target if not installed
  README.md
  rust-toolchain.toml
Labels: kind/enhancement

#573 Prevent openat from trapping on seccomp thread, by making it return EACCES instead
  src/hyperlight_host/src/sandbox/host_funcs.rs
  src/hyperlight_host/src/sandbox/initialized_multi_use.rs
  src/hyperlight_host/src/seccomp/guest.rs
  src/tests/rust_guests/simpleguest/src/main.rs
Labels: kind/bugfix

#574 Timeout rust job after 60 minutes
  .github/workflows/dep_rust.yml
Labels: kind/enhancement

#588 Remove version number from hyperlight-testing crate dependency
  Cargo.toml
  src/hyperlight_testing/Cargo.toml
Labels: kind/bugfix

#591 Update Crate descriptions for guest crates (#590)
  .github/workflows/CargoPublish.yml
  src/hyperlight_guest/Cargo.toml
  src/hyperlight_guest_bin/Cargo.toml
Labels: kind/bugfix

#594 Add additional checks on PR before auto approving
  dev/auto-approve-dependabot.sh
Labels: kind/enhancement

#417 Support ELF core dump creation on guest crash
  .github/workflows/dep_rust.yml
  Cargo.lock
  Justfile
  docs/how-to-debug-a-hyperlight-guest.md
  src/hyperlight_host/Cargo.toml
  src/hyperlight_host/build.rs
  src/hyperlight_host/src/hypervisor/crashdump.rs
  src/hyperlight_host/src/hypervisor/hyperv_linux.rs
  src/hyperlight_host/src/hypervisor/hyperv_windows.rs
  src/hyperlight_host/src/hypervisor/kvm.rs
  src/hyperlight_host/src/hypervisor/mod.rs
  src/hyperlight_host/src/hypervisor/windows_hypervisor_platform.rs
  src/hyperlight_host/src/sandbox/config.rs
  src/hyperlight_host/src/sandbox/uninitialized.rs
  src/hyperlight_host/src/sandbox/uninitialized_evolve.rs
  src/tests/rust_guests/witguest/Cargo.lock
Labels: kind/enhancement

#601 Allow hyperlight-host to build with x86_64-unknown-linux-musl target
  Justfile
  rust-toolchain.toml
  src/hyperlight_host/src/hypervisor/hyperv_linux.rs
  src/hyperlight_host/src/hypervisor/kvm.rs
  src/hyperlight_host/src/seccomp/guest.rs
Labels: kind/bugfix

#613 Updates for patch release v0.6.1
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: area/dependencies, kind/dependencies

#620 Remove duplicate derive Clone in macro
  src/hyperlight_component_macro/src/lib.rs
  src/hyperlight_component_util/src/rtypes.rs
  src/tests/rust_guests/callbackguest/Cargo.lock
  src/tests/rust_guests/simpleguest/Cargo.lock
Labels: kind/bugfix

#624 make socket component example work
  src/hyperlight_component_util/src/rtypes.rs
  src/hyperlight_host/tests/wit_test.rs
  src/tests/rust_guests/witguest/Cargo.lock
Labels: kind/bugfix

#556 Create GOVERNANCE.md
  GOVERNANCE.md
Labels: area/documentation, kind/enhancement

#639 [host] adds init-paging feature
  Justfile
  src/hyperlight_host/Cargo.toml
  src/hyperlight_host/src/hypervisor/hyperv_linux.rs
  src/hyperlight_host/src/hypervisor/hyperv_windows.rs
  src/hyperlight_host/src/hypervisor/kvm.rs
  src/hyperlight_host/src/hypervisor/mod.rs
  src/hyperlight_host/src/mem/elf.rs
  src/hyperlight_host/src/mem/layout.rs
  src/hyperlight_host/src/mem/memory_region.rs
  src/hyperlight_host/src/mem/mgr.rs
  src/hyperlight_host/src/sandbox/uninitialized_evolve.rs
Labels: kind/enhancement

#662 Don't log expected error on each guest function call
  src/hyperlight_common/src/flatbuffer_wrappers/guest_error.rs
  src/hyperlight_host/src/mem/mgr.rs
  src/hyperlight_host/src/mem/shared_mem.rs
Labels: kind/bugfix

#661 Update kvm-bindings to 0.13 and kvm-ioctls to 0.23
  Cargo.lock
  src/hyperlight_host/Cargo.toml
Labels: kind/dependencies

#572 Remove support for building PE files from hyperlight-guest-bin build.rs
  src/hyperlight_guest_bin/.cargo/config.toml
  src/hyperlight_guest_bin/build.rs
Labels: kind/enhancement

#668 Prep for v0.7.0 release
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/tests/rust_guests/callbackguest/Cargo.lock
  src/tests/rust_guests/simpleguest/Cargo.lock
Labels: kind/dependencies
