Repository hyperlight-dev/hyperlight, pull requests merged in 2025-04, with the labels that each got.

#388 changelog: fix version typo
  CHANGELOG.md
Labels: area/documentation, kind/dependencies

#390 Fix dependabot
  .github/dependabot.yml
  Cargo.toml
Labels: kind/dependencies

#396 Fix dependabot for issues with test guests and mshv crates
  .github/dependabot.yml
Labels: kind/dependencies

#385 Fix racecondition in hypervisor-handler thread
  src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
Labels: kind/bugfix

#410 Fix issues in guest logging
  docs/hyperlight-metrics-logs-and-traces.md
  src/hyperlight_host/src/hypervisor/hyperv_linux.rs
  src/hyperlight_host/src/hypervisor/hyperv_windows.rs
  src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
  src/hyperlight_host/src/hypervisor/inprocess.rs
  src/hyperlight_host/src/hypervisor/kvm.rs
  src/hyperlight_host/src/hypervisor/mod.rs
  src/hyperlight_host/src/sandbox/outb.rs
  src/hyperlight_host/src/sandbox/uninitialized.rs
  src/hyperlight_host/src/sandbox/uninitialized_evolve.rs
  src/hyperlight_host/tests/integration_test.rs
  src/hyperlight_testing/src/logger.rs
  src/hyperlight_testing/src/simplelogger.rs
Labels: kind/enhancement

#409 Fix issue label checker
  .github/workflows/IssueLabelChecker.yml
Labels: kind/bugfix

#411 Add GH job and script to auto approve dependabot PRs.
  .github/dependabot.yml
  .github/workflows/auto-merge-dependabot.yml
  dev/auto-approve-dependabot.sh
Labels: kind/enhancement

#415 readme: make example info clear
  README.md
Labels: kind/enhancement

#416 Update dependabot autocommit script and job
  .github/workflows/auto-merge-dependabot.yml
  dev/auto-approve-dependabot.sh
Labels: kind/dependencies

#421 fix: Add -fPIC option for building C guests.
  c.just
Labels: kind/bugfix

#422 Fix confusing log message when checking present hypervisor
  src/hyperlight_host/src/hypervisor/hyperv_linux.rs
  src/hyperlight_host/src/hypervisor/kvm.rs
  src/hyperlight_host/src/hypervisor/windows_hypervisor_platform.rs
  src/tests/rust_guests/callbackguest/Cargo.lock
  src/tests/rust_guests/simpleguest/Cargo.lock
Labels: kind/bugfix

#419 Clean up justfile and testing
  .github/workflows/dep_rust.yml
  Justfile
  src/hyperlight_common/Cargo.toml
  src/hyperlight_host/examples/guest-debugging/main.rs
  src/hyperlight_host/examples/logging/main.rs
  src/hyperlight_host/examples/tracing/main.rs
  src/hyperlight_testing/Cargo.toml
Labels: kind/enhancement
