Repository hyperlight-dev/hyperlight, pull requests merged in 2025-03, with the labels that each got.

#291 devcontainer: install gdb and vscode ext for debugging
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: area/process

#323 Fix CI rust toolchain
  .github/workflows/dep_rust.yml
Labels: area/process

#301 Add fuzzing target to fuzz return type and parameters
  .github/workflows/Fuzzing.yml
  .github/workflows/ValidatePullRequest.yml
  .github/workflows/dep_fuzzing.yml
  Cargo.lock
  Cargo.toml
  Justfile
  fuzz/.gitignore
  fuzz/Cargo.toml
  fuzz/README.md
  fuzz/doc-assets/image.png
  fuzz/fuzz_targets/guest_call.rs
  fuzz/fuzz_targets/host_call.rs
  fuzz/fuzz_targets/host_print.rs
  rust-toolchain.toml
  src/hyperlight_common/Cargo.toml
  src/hyperlight_common/src/flatbuffer_wrappers/function_types.rs
  src/hyperlight_common/src/lib.rs
  src/hyperlight_host/Cargo.toml
  src/hyperlight_host/fuzz/Cargo.toml
  src/hyperlight_host/src/hypervisor/hyperv_linux.rs
  src/hyperlight_host/src/hypervisor/hyperv_windows.rs
  src/hyperlight_host/src/hypervisor/kvm.rs
  src/tests/rust_guests/simpleguest/src/main.rs
Labels: area/process, kind/refactor

#326 fix devconatiner permission issue while after container starts/restarts
  .devcontainer/devcontainer.json
Labels: area/process

#335 Add a specific CI job on which we can gate PRs.
  .github/workflows/ValidatePullRequest.yml
Labels: area/process

#324 Update fuzzing test to check for simpleguest in same directory as executable
  .github/workflows/Fuzzing.yml
  .github/workflows/ValidatePullRequest.yml
  Justfile
  fuzz/Cargo.toml
  fuzz/README.md
  fuzz/fuzz_targets/guest_call.rs
  fuzz/fuzz_targets/host_call.rs
  fuzz/fuzz_targets/host_print.rs
  src/hyperlight_testing/src/lib.rs
Labels: rust

#336 Fix release workflow
  .github/workflows/CreateRelease.yml
Labels: area/process

#334 dbg: update guest debugging docs to explain how to use lldb in vscode
  docs/how-to-debug-a-hyperlight-guest.md
Labels: area/documentation

#342 Increase fuzzing memory limit
  Justfile
Labels: area/process

#344 Build fuzzing targets with debuginfo
  Justfile
Labels: area/security, area/process

#349 Remove unused justfile
  src/hyperlight_host/Justfile
Labels: area/process

#354 Using ci-workflow-setup@v1.3.0 to use clang18 on Ubuntu runners
  .github/workflows/Benchmarks.yml
  .github/workflows/CargoPublish.yml
  .github/workflows/CreateRelease.yml
  .github/workflows/dep_build_guest_binaries.yml
  .github/workflows/dep_fuzzing.yml
  .github/workflows/dep_rust.yml
Labels: area/process

#353 readme update for Slack details to point to CNCF #hyperlight
  README.md
Labels: area/documentation, lifecycle/confirmed

#360 Remove unused cargo dependency and cleanup workspace cargo.toml
  Cargo.toml
  src/hyperlight_host/Cargo.toml
Labels: area/process

#298 Document label meaning
  docs/github-labels.md
Labels: area/process

#352 Add deny lints to hyperlight-host crate
  src/hyperlight_host/src/lib.rs
  src/hyperlight_host/src/sandbox_state/sandbox.rs
  src/hyperlight_host/src/sandbox_state/transition.rs
Labels: area/documentation

#370 Switch release job to use linux runner
  .github/workflows/CreateRelease.yml
Labels: kind/bugfix, area/infrastructure

#371 Fix benchmark artifact names in release job
  .github/workflows/CreateRelease.yml
Labels: kind/enhancement, area/infrastructure

#372 Fix filename typo in release workflow
  .github/workflows/CreateRelease.yml
Labels: kind/enhancement, area/infrastructure

#378 Fixes label for GH action updates
  .github/dependabot.yml
Labels: kind/bugfix

#327 Gdb support for mshv guests
  .github/workflows/dep_rust.yml
  Justfile
  docs/debugging-hyperlight.md
  docs/how-to-debug-a-hyperlight-guest.md
  src/hyperlight_host/build.rs
  src/hyperlight_host/examples/guest-debugging/main.rs
  src/hyperlight_host/src/hypervisor/gdb/event_loop.rs
  src/hyperlight_host/src/hypervisor/gdb/kvm_debug.rs
  src/hyperlight_host/src/hypervisor/gdb/mod.rs
  src/hyperlight_host/src/hypervisor/gdb/mshv_debug.rs
  src/hyperlight_host/src/hypervisor/gdb/x86_64_target.rs
  src/hyperlight_host/src/hypervisor/hyperv_linux.rs
  src/hyperlight_host/src/hypervisor/hypervisor_handler.rs
  src/hyperlight_host/src/hypervisor/kvm.rs
Labels: kind/enhancement

#381 release: change crate version to v0.3.0 and update CHANGELOG.md
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
Labels: area/infrastructure, kind/dependencies

#382 release: update rust tests deps to latest hyperlight version
  src/tests/rust_guests/callbackguest/Cargo.lock
  src/tests/rust_guests/simpleguest/Cargo.lock
Labels: kind/dependencies
