Repository hyperlight-dev/hyperlight, pull requests merged in 2025-09, with the labels that each got.

#869 Change of Error Code for Exception enum TryFrom<u8> impl
  src/hyperlight_common/src/outb.rs
  src/tests/rust_guests/callbackguest/Cargo.lock
  src/tests/rust_guests/simpleguest/Cargo.lock
Labels: kind/bugfix

#876 Add missing benchmark runs for windows server 2025
  .github/workflows/Benchmarks.yml
Labels: kind/enhancement

#880 Update common workflow
  .github/workflows/Benchmarks.yml
  .github/workflows/CargoPublish.yml
  .github/workflows/CreateRelease.yml
  .github/workflows/copilot-setup-steps.yml
  .github/workflows/dep_build_guest_binaries.yml
  .github/workflows/dep_fuzzing.yml
  .github/workflows/dep_rust.yml
Labels: kind/dependencies

#882 Add benchmark for measuring performance impact on moving sandbox across thread
  src/hyperlight_host/benches/benchmarks.rs
  src/tests/rust_guests/witguest/Cargo.lock
Labels: kind/enhancement, area/performance

#879 Remove old code used for removed in-process feature
  src/hyperlight_host/src/mem/layout.rs
  src/hyperlight_host/src/mem/mgr.rs
  src/hyperlight_host/src/mem/shared_mem.rs
  src/hyperlight_host/src/mem/shared_mem_snapshot.rs
  src/hyperlight_host/src/sandbox/initialized_multi_use.rs
Labels: kind/refactor

#891 Update mshv crates for Azure Linux to v0.6.1
  Cargo.lock
  src/hyperlight_host/Cargo.toml
  src/hyperlight_host/src/hypervisor/hyperv_linux.rs
Labels: kind/dependencies

#884 Remove MemMgrWrapper and WrapperGetter
  src/hyperlight_host/src/func/guest_err.rs
  src/hyperlight_host/src/func/host_functions.rs
  src/hyperlight_host/src/hypervisor/gdb/mod.rs
  src/hyperlight_host/src/hypervisor/hyperv_linux.rs
  src/hyperlight_host/src/hypervisor/hyperv_windows.rs
  src/hyperlight_host/src/hypervisor/kvm.rs
  src/hyperlight_host/src/hypervisor/mod.rs
  src/hyperlight_host/src/lib.rs
  src/hyperlight_host/src/mem/mgr.rs
  src/hyperlight_host/src/sandbox/initialized_multi_use.rs
  src/hyperlight_host/src/sandbox/mem_mgr.rs
  src/hyperlight_host/src/sandbox/mod.rs
  src/hyperlight_host/src/sandbox/outb.rs
  src/hyperlight_host/src/sandbox/uninitialized.rs
  src/hyperlight_host/src/sandbox/uninitialized_evolve.rs
Labels: kind/refactor

#893 Add benchmark for measuring time to interrupt a sandbox
  src/hyperlight_host/benches/benchmarks.rs
Labels: kind/enhancement, area/performance

#895 Refactor evolve code to be simpler
  src/hyperlight_host/src/sandbox/mod.rs
  src/hyperlight_host/src/sandbox/uninitialized.rs
  src/hyperlight_host/src/sandbox/uninitialized_evolve.rs
Labels: kind/refactor

#923 Pin to Debian 12 (bookworm) for Dev image and fix for Nightly
  .devcontainer/Dockerfile
  .github/workflows/RustNightly.yml
Labels: kind/dependencies
