Repository hyperlight-dev/hyperlight, pull requests merged in 2025-08, with the labels that each got.

#755 fix(guest-bin): move logger initialization
  src/hyperlight_guest_bin/src/lib.rs
Labels: kind/enhancement

#766 Give release-blocker-action permission to read github issues
  .github/workflows/CreateRelease.yml
Labels: kind/bugfix

#771 Introduce a separate KVM error variant of HyperlightError.
  Cargo.lock
  src/hyperlight_host/Cargo.toml
  src/hyperlight_host/src/error.rs
  src/hyperlight_host/src/hypervisor/hyperv_linux.rs
Labels: kind/bugfix

#773 Updates for v0.8.0 release
  .github/workflows/CargoPublish.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/tests/rust_guests/callbackguest/Cargo.lock
  src/tests/rust_guests/simpleguest/Cargo.lock
  typos.toml
Labels: kind/dependencies

#777 fix release blocker so it only blocks on release branches
  .github/workflows/ReleaseBlockerCheck.yml
Labels: kind/bugfix

#753 fix(guest-bin): align user memory allocations
  src/hyperlight_guest_bin/src/memory.rs
Labels: kind/enhancement

#830 Ran cargo update, updated dependabot to run against workspace exclude…
  .github/dependabot.yml
  Cargo.lock
  src/tests/rust_guests/callbackguest/Cargo.lock
  src/tests/rust_guests/dummyguest/Cargo.lock
  src/tests/rust_guests/simpleguest/Cargo.lock
  src/tests/rust_guests/witguest/Cargo.lock
Labels: kind/dependencies

#827 Fix unbounded growth of panic hook after each new sandbox
  src/hyperlight_host/src/signal_handlers/mod.rs
Labels: kind/bugfix

#840 Fixes to Host Call Fuzzing
  fuzz/fuzz_targets/host_call.rs
  src/hyperlight_host/src/sandbox/initialized_multi_use.rs
Labels: kind/bugfix

#839 Make the component macros support passing host resources to guests
  Justfile
  flake.nix
  src/hyperlight_component_util/src/emit.rs
  src/hyperlight_component_util/src/guest.rs
  src/hyperlight_component_util/src/hl.rs
  src/hyperlight_component_util/src/host.rs
  src/hyperlight_component_util/src/rtypes.rs
  src/hyperlight_host/tests/wit_test.rs
  src/tests/rust_guests/witguest/Cargo.lock
  src/tests/rust_guests/witguest/Cargo.toml
  src/tests/rust_guests/witguest/guest.wit
  src/tests/rust_guests/witguest/src/main.rs
Labels: kind/bugfix
